# This is a basic workflow to help you get started with Actions

name: AUTO_UPDATE_CCG_BIB

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *' # Runs at 00:00 UTC on the 1st of every month

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download_ccg_bib:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Checks out 
      - name: download ccg.bib
        run: wget https://cogcomp.seas.upenn.edu/bib/ccg.bib
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update ccg.bib from the CCG website
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: auto_update_ccg_bib
          delete-branch: true
          title: '[Auto-Update] Updated ccg.bib from the CCG website'
          body: |
            Automatically downloading ccg.bib from the CCG website and update it here

          assignees: schen149
          reviewers: schen149

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
